# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker
# -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apisolid
# -p 5430:5432 bitnami/postgresql

# docker compose up -d => inicia o docker em background, por debaixo dos panos.
# docker compose stop => pausa meu docker
# docker compose down  => deleta o docker

version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
